# BAG OF WORDS

In [1]:
!pip install scikit-learn

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data/nlp.csv", index_col=0)
df.head

<bound method NDFrame.head of                                                   Text
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...
3    9. Baidu Research: Çin'in önde gelen arama mot...
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...
..                                                 ...
853  doğal dil işleme alanında yüksek lisans-doktor...
854                           dogal dil isleme şeyleri
855  Bir veri madenciliği ve doğal dil işleme uygul...
856  "Doğal dil işleme" ile ilgili deneyimi olan ya...
857  Haftaya öğrencilik hayatıma kaldığım yerden de...

[858 rows x 1 columns]>

In [5]:
import on_islem

In [6]:
df["Text_2"] = df["Text"].apply(on_islem.pre_processing)
df["Text_2"] = df["Text_2"].apply(on_islem.remove_space)
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [7]:
# Boş liste kontrolü
df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [8]:
df_index = df[df["Text_2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()
del df ["index"]
        
df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [9]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [10]:
df["Text_2"]

0      [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, olduğunu, iç, önemli, o...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                                   [dogal, dil, isle]
852       [ver, madencilik, doğal, dil, işle, uygulamas]
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 855, dtype: object

In [11]:
df["Text_3"] = [' '.join(w for w in item) for item in df["Text_2"]]
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka olduğunu iç önemli olduk kı...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [37]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())
X

<855x4785 sparse matrix of type '<class 'numpy.int64'>'
	with 16935 stored elements in Compressed Sparse Row format>

In [38]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
X[0]

<1x4785 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [40]:
df["Text_4"] = X.toarray().tolist()
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [41]:
set(X.toarray()[0].tolist())

{0, 1, 2, 3, 4}

In [42]:
vectorizer.vocabulary_.keys()

dict_keys(['yapay', 'zeka', 'nedir', 'işe', 'yarar', 'yz', 'bilgisayar', 'diğer', 'cihazların', 'in', 'benzer', 'şekil', 'düşünmesini', 'öğrenmesini', 'karar', 'verme', 'proble', 'çözme', 'sağlaya', 'bil', 'dalıdır', 'teknolojisi', 'doğal', 'dil', 'işleme', 'ses', 'tanıma', 'gör', 'veri', 'analiz', 'edin', 'chatgptyi', 'kullanarak', 'işle', 'nlp', 'yetenek', 'faydalanarak', 'en', 'sa', 'ürün', 'nelerdir', 'müşter', 'tutma', 'ora', 'gip', 'soru', 'sor', 'chatgpt', 'dayal', 'içgörü', 'sağlasın', 'öncelik', 'olduğunu', 'iç', 'önemli', 'olduk', 'kısaç', 'inceleyelim', 'ai', 'kendi', 'verecek', 'programla', 'sürecidir', 'bu', 'mak', 'öğrenimi', 'tahm', 'analitik', 'çeşitli', 'yönte', 'yapılabilir', 'baidu', 'research', 'çin', 'ön', 'gele', 'ara', 'motor', 'baidun', 'araştırma', 'ola', 'otono', 'araç', 'teknoloji', 'üzer', 'çalışmaktadır', 'twitter', 'hesapları', 'microsoft', 'odaklana', 'robotik', 'sistem', 'openai', 'dünya', 'şirket', 'geliş', 'otomatik', 'öğrenme', 'olarak', 'görüntü', 'm

# TF - IDF

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())

In [49]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [50]:
set(X.toarray()[0])

{0.0,
 0.03508115658001388,
 0.03685011328026531,
 0.12317029281566404,
 0.1287180325367376,
 0.1293951901484212,
 0.14937145922687903,
 0.15331933006757356,
 0.15474585010773745,
 0.15623579147571884,
 0.1669097751456677,
 0.17386946496025046,
 0.1765523493830673,
 0.19014279446116142,
 0.19978536869856103,
 0.20581084119178317,
 0.21337581377665515,
 0.22232665378265135,
 0.22301838801405474,
 0.2366088330921489,
 0.3162294875300779}

In [51]:
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
..                                                 ...  
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[855 rows x 4 columns]

In [52]:
df["Text_5"] = X.toarray().tolist()
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [53]:
len(X.toarray()[0])

4785

# Word2vec

In [54]:
!pip install gensim

     -------------------------------------- 67.1/67.1 kB 121.3 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20448 sha256=9fb01275b20dabbbf799a91a551e3ccf1bb8645a264362b6fb50295ce676edb1
  Stored in directory: c:\users\ayahm\appdata\local\pip\cache\wheels\01\02\ee\df0699282986903a384b69aab4413af9efd26b3612b5dccc9e
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3522 sha256=81007d25f6eb33de0bd9b784742406b0012d00d2db35a71e831514482e23b86d
  Stored in directory: c:\users\ayahm\appdata\local\pip\cache\wheels\43\aa\48\5c66b931ff013ad19774081aa19656637af5c0cc33b5494b30
Successfully built fst-pso miniful


In [57]:
from gensim.models import Word2Vec

In [58]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [59]:
model = Word2Vec(sentences = df["Text_2"].tolist(), vector_size=100, window=5, min_count=1)
model.save("data/word2vec.model")

In [60]:
print(model)

Word2Vec<vocab=4796, vector_size=100, alpha=0.025>


In [61]:
words = list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [62]:
len(words)

4796

In [63]:
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [65]:
model.wv.key_to_index["yapay"]

3

In [66]:
model.wv[3]

array([-0.08181268,  0.18435456,  0.06450721, -0.06997507,  0.00263556,
       -0.30468705,  0.07172316,  0.4224716 , -0.18534197, -0.10600045,
       -0.03670961, -0.36140501,  0.00897565,  0.14734006, -0.00179096,
       -0.15867077,  0.05093582, -0.25702235, -0.04758081, -0.44462606,
        0.03613527, -0.00870115,  0.18288769, -0.08100646, -0.05749778,
       -0.00739101, -0.1066303 , -0.05884157, -0.17719863,  0.07875686,
        0.24243753, -0.01118536,  0.0583236 , -0.19880758, -0.04122486,
        0.23097087,  0.10329454, -0.23397593, -0.12775768, -0.32687217,
        0.0428267 , -0.20238173, -0.06204474, -0.02234214,  0.16602337,
       -0.11993967, -0.22182152, -0.02689659,  0.08601232,  0.11727407,
        0.0527326 , -0.15731241, -0.06176149,  0.02790322, -0.13500309,
        0.02677794,  0.1511709 , -0.09280867, -0.17364705, -0.00531962,
        0.06301235,  0.06002983,  0.07335546,  0.06698074, -0.21529292,
        0.22440262,  0.08058102,  0.14422299, -0.24633119,  0.25

In [68]:
model.wv.get_vector("yapay")

array([-0.08181268,  0.18435456,  0.06450721, -0.06997507,  0.00263556,
       -0.30468705,  0.07172316,  0.4224716 , -0.18534197, -0.10600045,
       -0.03670961, -0.36140501,  0.00897565,  0.14734006, -0.00179096,
       -0.15867077,  0.05093582, -0.25702235, -0.04758081, -0.44462606,
        0.03613527, -0.00870115,  0.18288769, -0.08100646, -0.05749778,
       -0.00739101, -0.1066303 , -0.05884157, -0.17719863,  0.07875686,
        0.24243753, -0.01118536,  0.0583236 , -0.19880758, -0.04122486,
        0.23097087,  0.10329454, -0.23397593, -0.12775768, -0.32687217,
        0.0428267 , -0.20238173, -0.06204474, -0.02234214,  0.16602337,
       -0.11993967, -0.22182152, -0.02689659,  0.08601232,  0.11727407,
        0.0527326 , -0.15731241, -0.06176149,  0.02790322, -0.13500309,
        0.02677794,  0.1511709 , -0.09280867, -0.17364705, -0.00531962,
        0.06301235,  0.06002983,  0.07335546,  0.06698074, -0.21529292,
        0.22440262,  0.08058102,  0.14422299, -0.24633119,  0.25

In [69]:
def word2vec(value):
    model = Word2Vec.load("data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)
    
    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
        
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [70]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [71]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [72]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.034793805330991745, 0.07460851222276688, 0...  
1  [-0.023401614278554916, 0.05379101261496544, 0...  
2  [-0.029055651277303696, 0.07019397616386414, 0...  
3  [-0.02762702666223049, 0.060655850917100906, 0...  
4  [-0.038288190960884094, 0.08555429428815842, 0...

In [12]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1  veri analiz edin chatgptyi kullanarak doğal di...  
2  öncelik yapay zeka olduğunu iç önemli olduk kı...  
3  baidu research çin ön gele ara motor baidun ar...  
4  microsoft ai microsoft yapay zeka teknoloji od...

In [14]:
df["bow"] = on_islem.bag_of_words(df["Text_3"])
df["tf-idf"] = on_islem.tf_idf(df["Text_3"])
df["word2vec"] = df["Text_2"].apply(on_islem.word2vec)

In [15]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                                 bow  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              tf-idf  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.034793805330991745, 0.07460851222276688, 0...  
1  [-0.023401614278554916, 0.05379101261496544, 0...  
2  [-0.029055651277303696, 0.07019397616386414, 0...  
3  [-0.02762702666223049, 0.060655850917100906, 0...  
4  [-0.038288190960884094, 0.08555429428815842, 0...